version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    environment:
      - SERVER_HOST
      - SERVER_PORT
      - DB_NAME
      - DB_HOST=db
      - DB_PORT
      - DB_USER
      - DB_PASSWORD
      - DB_PROTOCOL
      - DB_TEST_URL
    ports:
      - 80:${SERVER_PORT}
    env_file:
      - ./.env
    networks:
      - server-side
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PGPORT: ${DB_PORT}
    networks:
      - server-side
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  server-side:

volumes:
  db-data:
